import { spinner } from "@clack/prompts";
import { execa } from "execa";
import path from 'path'
import fs from 'fs'
import { getReadmeCode, globalsCss, nextPageCode, nodeIndex, getNodePackage, nuxtApp, nuxtConfig, sveltePage, svelteHead, gitignore } from "./templates";

const s = spinner();

function replaceFavicon(targetDir: string, dest: string) {
  const currentFileUrl = new URL(import.meta.url)
  const __dirname = path.dirname(currentFileUrl.pathname)
  const faviconSource = path.resolve(__dirname, '..', 'assets', 'favicon.ico')
  const faviconDest = path.resolve(targetDir, dest)
  fs.copyFileSync(faviconSource, faviconDest)
}

// Next JS
export async function setupNext(targetDir: string, pkInstall: string, dirName: string) {
  s.start('Setting up Next JS Project');
  await execa`${pkInstall} create-next-app@latest ${targetDir} --yes --empty --skip-install --disable-git --biome`;

  // Change metadata
  const layoutPath = path.resolve(targetDir, 'app/layout.tsx')
  fs.writeFileSync(layoutPath, fs.readFileSync(layoutPath, 'utf8').replace('Create Next App', 'Empty'));
  fs.writeFileSync(layoutPath, fs.readFileSync(layoutPath, 'utf8').replace('Generated by create next app', 'This is an empty project'));

  // Copy favicon from assets to app directory
  replaceFavicon(targetDir, 'app/favicon.ico')

  fs.writeFileSync(path.join(targetDir, 'app/page.tsx'), nextPageCode)
  fs.writeFileSync(path.join(targetDir, 'app/globals.css'), globalsCss)
  fs.writeFileSync(path.join(targetDir, 'README.md'), getReadmeCode(dirName))

  s.stop('Next JS Project created!');
}

// Nuxt
export async function setupNuxt(targetDir: string, pkInstall: string, dirName: string, packageManager: string) {
  s.start('Setting up Nuxt Project');
  await execa`${pkInstall} create-nuxt@latest ${targetDir} --template=minimal --force --no-install --no-modules --gitInit=false --packageManager=${packageManager}`

  fs.writeFileSync(path.join(targetDir, 'app/app.vue'), nuxtApp)
  fs.writeFileSync(path.join(targetDir, 'app/globals.css'), globalsCss)
  
  // add css + metadata to config
  const originalConfig = fs.readFileSync(path.join(targetDir, 'nuxt.config.ts'), 'utf8')
  const dateMatch = originalConfig.match(/compatibilityDate:\s*'([^']+)'/)
  const compatibilityDate = dateMatch ? dateMatch[1] : '2026-01-01'
  fs.writeFileSync(path.join(targetDir, 'nuxt.config.ts'), nuxtConfig.replace('0000-00-00', compatibilityDate))

  replaceFavicon(targetDir, "public/favicon.ico")
  fs.rmSync(path.join(targetDir, 'public/robots.txt'), { force: true })
  fs.writeFileSync(path.join(targetDir, 'README.md'), getReadmeCode(dirName))

  s.stop('Nuxt Project created!');
}

export async function setupNode(targetDir: string, pkInstall: string, dirName: string) {
  s.start('Setting up Node Project');

  // Create the target directory if it doesn't exist
  if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
  }
  
  fs.writeFileSync(path.join(targetDir, 'package.json'), getNodePackage(dirName))
  fs.writeFileSync(path.join(targetDir, 'index.mts'), nodeIndex)

  s.stop('Node Project created!');
}

export async function setupSvelte(targetDir: string, pkInstall: string, dirName: string, packageManager: string) {
  s.start('Setting up Svelte Project');
  await execa(pkInstall, ['sv', 'create', '--template', 'minimal', '--types', 'ts', '--add', 'tailwindcss=plugins:none', '--no-install', targetDir], { stdio: 'ignore' })
  
  // Delete stuff
  fs.rmSync(path.join(targetDir, '.vscode'), { recursive: true, force: true })
  fs.rmSync(path.join(targetDir, 'static'), { recursive: true, force: true })
  fs.rmSync(path.join(targetDir, '.npmrc'), { force: true })
  fs.rmSync(path.join(targetDir, 'src/lib/assets/favicon.svg'), { force: true })

  // Replace adapter '@sveltejs/adapter-auto'
  if (packageManager == 'bun') {
      const svelteConfigPath = path.join(targetDir, 'svelte.config.js')
      fs.writeFileSync(svelteConfigPath, fs.readFileSync(svelteConfigPath, 'utf-8').replace("'@sveltejs/adapter-auto'", "'svelte-adapter-bun'"))
  }

  // Replace svelte:head in +layout.svelte and copy favicon
  fs.writeFileSync(
      path.join(targetDir, 'src/routes/+layout.svelte'),
      fs.readFileSync(path.join(targetDir, 'src/routes/+layout.svelte'), 'utf8')
          .replace(/<svelte:head>[\s\S]*?<\/svelte:head>/, svelteHead)
          .replace("'./layout.css'", "'./globals.css'")
          .replace("'$lib/assets/favicon.svg'", "'$lib/assets/favicon.ico'")
  );

  fs.writeFileSync(path.join(targetDir, 'src/routes/+page.svelte'), sveltePage)
  fs.rmSync(path.join(targetDir, 'src/routes/layout.css'), { force: true })
  fs.writeFileSync(path.join(targetDir, 'src/routes/globals.css'), globalsCss)

  replaceFavicon(targetDir, 'src/lib/assets/favicon.ico')

  fs.writeFileSync(path.join(targetDir, 'README.md'), getReadmeCode(dirName))

  s.stop('Svelte Project created!');
}

export async function installDependencies(targetDir: string, packageManager: string, projectType: string) {
  s.start(`Installing dependencies`);

  // Add tailwind dependencies if using nuxt
  if (projectType === 'nuxt') {
      await execa(packageManager.toString(), ['install', 'tailwindcss', '@tailwindcss/vite'], { cwd: targetDir, stdio: ["ignore", "ignore", "pipe"], windowsHide: true })
  }
  
  // * Regular 'npm install'
  await execa(packageManager.toString(), ['install'], { cwd: targetDir, stdio: ["ignore", "ignore", "pipe"], windowsHide: true })

  // Add dev dependencies if using node
  if (projectType === 'node') {
      await execa(packageManager.toString(), ['install', '-D', '@types/node', 'dotenv', 'tsx', 'typescript'], { cwd: targetDir, stdio: ["ignore", "ignore", "pipe"], windowsHide: true })
  }

  // Add bun adapter if using bun & svelte
  if (packageManager === 'bun' && projectType === 'svelte') {
      await execa('bun', ['add', '-D', 'svelte-adapter-bun'], { cwd: targetDir, stdio: ["ignore", "ignore", "pipe"], windowsHide: true })
  }

  s.stop(`Installed via ${packageManager}`);
}
export async function initializeGit(targetDir: string) {
  s.start("Initializing git");
  await execa("git", ["init"], {
      cwd: path.resolve(targetDir),
      stdio: "ignore",
      windowsHide: true,
  })

  const gitignorePath = path.resolve(targetDir, ".gitignore");
  if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, gitignore);
  }

  await execa("git", ["add", "."], {
      cwd: path.resolve(targetDir),
      stdio: "ignore",
      windowsHide: true,
  })

  await execa("git", ["commit", "-m", '"Initial commit"'], {
      cwd: path.resolve(targetDir),
      stdio: "ignore",
      windowsHide: true,
  })

  s.stop("Git initialized");
}